# Generated by Django 3.0rc1 on 2020-04-02 04:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Message', django_mysql.models.ListCharField(models.CharField(max_length=256), max_length=2560000, size=None)),
            ],
        ),
    ]
