# Generated by Django 3.0rc1 on 2020-01-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dp', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('department', models.CharField(max_length=100)),
                ('part', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
