# Generated by Django 3.0rc1 on 2020-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_registered',
            field=models.CharField(default='', max_length=100),
        ),
    ]
