# Generated by Django 3.0rc1 on 2020-01-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_course_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('part', models.CharField(max_length=100)),
                ('People', models.CharField(max_length=100000)),
            ],
        ),
    ]
