# Generated by Django 3.0rc1 on 2020-01-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_materials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
    ]
